from extensions import *
from helpers import *
from graphlib import *
from alignment import *

# Lesson 3 - Week 2

# 1.2.3 - Global Alignment
if run(1):
   score, s = globalAlignment('PLEASANTLY', 'MEANLY')
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''8
PLEASANTLY
-MEA--N-LY''')

   l = readlines('dataset_247_3.txt')
   score, s = globalAlignment(l[0], l[1])
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''2155
R--------EFNAHWSDDCLQEQPTYCFITGNFRQVMRW-GELASQVKNNFKHGRGKHALAAQQQRAKWNWWNYHYQYSMSNRWGTYCEKTFMLFRVIPSMDENA-GYEDSN-E-AGCHMLNGHCTVRPGGMPFQAIGWQRLQGHIQVDGTVAMFDYYS--AN-W---W---SY------S-CMVASWNQNLA-ISYANLPMERRQANFMCENVGHMVFNNKNCPWEQGLHKHDAFPNMNLELPIRMWCDSIKPGNPNQSHPLNKYKRPMVQ-D-MDAIKQTYHWMYGHPMEWNRTTARPSFIIMGNICNPLSFHMGPMFSLWIVAYGDTVTYWGEKIEDNHRMQPLTLNYTLCTPNRHWSSPLIYRYWYGRFG---EP---Y-MN-YPSIDRILWGSIDY--PNQRKNEERCGWKKEMFDAHCRWCADDPFHWCAAYGVPR-RLF--FSRGSMYMSCMQWITIAYVKAICLQYSCKLPPPVYRVITMGDPWHYLQQMELNQLPSCC---EAQWHRNYTTDFWGSCGDF-M-------QLDEGQSNV--AT-----PNARFVHR--RVEFMCPAGQNSGCAAERDYM-GLCIYASDSVTDGLANVDFFFLTDPQPSLPVKMMHEICPCLHSFDSQMHPIVWVEHPI-M--QAGFDLTYAAVQGGFRTDQ-C------PGKSNCEDMGPWYKRELYKHWVQWIADLIFQG-QNDT-EHSKIQKTKCRFEIERQWAHD-GGHFYGCFVRWEFFSITY-Y--FTPGNQPDM-C------WARNRKVCVMA--WMQNNGHKLGYYSIENCIEKA
RHTHGMLYCQFNFHWSDDCL----LYLIFFDNFRQVYKCDNKIAKQVLNNFKHGRGKHALAAQQARAKCNWWNYHYQYSMSNRWGTYCEKTFYLFRVIAS-NHSANGYRDSNVHFIGAHMLNGHCTVRPRGMHFQQ-GHIQVDGTDEKWMNTAMFDYRSSWAQAWLTNWDCCSYTCTWMASMCMVASWNQNLADSSYANLPMERRQANFMCENVGH--HKHMYF-WVV-TEGYNG-PNMNLEDPIRMWSQSIKPGN---SHPLNKYKRPQVQLKCMDAIKQTYHWMYGHPMEWN-TT-----IIMGNICNVLSFHMGPMF-----C----VTYWGEKYEDNHRMQPLWLNYTLCTPNRHWSSPLIYRYWYGRFGITWHVCRWYPCSQYPSQDRILW--IDYIGPDGWMFNQRVNEEREMFDAHCRWCADDPFHWCAAYGVPQMELWRMYKEGPG--SCMQWITIAYVKAICLEQGMQYH--LWRVITMGDPWHYLQQMELNQLPSCIMLVEAQWHRNYTTDMWGSCGDFKMSIKGERMQLDEGQSNVTVATSCIFTPNARFVHRWVNVEFMCIAG--F--AAERDVTDGLANVKSWA-TPH-T-M-FFFLTDPQPSLPV-YM----PCLH-----MHPIVWVEHPICICWKAAGDLTYAAVQGGFRTDQWMTDDMHRPGKSNCEDMGPWYKRELYKHGGHY-QS--FQWFQNDTCGHYTRQKNKCRFEIERQWAFDLPWMLCGCFVYWEFFSITYRMNLFTPGNQPDMECQLENETWARVRKVCVMAISQMQNNGHKLGYYRIENCIEKA''')


# 1.2.10 - Local Alignment
if run(2):
   score, s = localAlignment('MEANLY', 'PENALTY')
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''15
EANL-Y
ENALTY''')

   l = readlines('dataset_247_10.txt')
   score, s = localAlignment(l[0], l[1])
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''1112
FYFYPSYMTQFRSYWTANE-N-KLMTYLTTYEDGKSHSCCDQCTIVTSCKMMKCEG-HLYSCGFGNTEGPNQRVPAENWTCITCSISTICVALEQLF-LTKFDIQTKDIQTVDIDVQWVAK-KGSPFD-R-YIPHGKQCVHDAAPYGWLSSSSANMMCCHAGECYWEPLE-ETKDDRPKFTTETDLFGFMGTTGVGCMGEKHIIHERCSLDSPESSHEEPVKVERLEMPRTLVHRYR--Y--WNKFLNCRYSPHIVQAM--EMYYKN--IKC-VFNWDRWRIVTILYSFIQRFNILTVWQYHFKEMNKLDMFAVSGCGNYKNHAW--YNAHTGQGNGKRLGIFSAVE--T-----YFHFTNMQRQQRPNTAPACYKMLFQVPMMLKYTTQNLTHARPITKTDVHYIMTPCCHGKRRPGLSVVGMCNHT-IPYDHRWDA-E-------MPMDHNYKEYCEADHDHQRKHWLCETTRKWSSTRPNQAATF--RGFIYSLIPVLF-------AF-VMYEQ-EE---QIDPF--K--KCERHGTSYETE-QS---PWPSDPETKQVIMKKSAD-R-W--GAWNRQCFE---M--W-TLPWTLGSHLKQLFDFDWISEIFILWCLLRWYKYLNQCTMARWW-R-SCN---PYNRMHVGREVAMRNKDEHIEIGFLFIDVTDLSNAIWSRLRTSCWLR--H-Y-VD-DKT-QKVEKC-WEWEDTMID-GNNTPHLRKI--NTRVSGMQTFFY--GDAYPCSGCSIIAAHHQT-AEDTKWP-FDPG--T-GNKR--M-ANTLPCGMKHE---AWKQPLHNANVINMAFYNGAEADFAHLVWMS--FG-KHAF--FMKKRSAIHWN--WH-K-W-WVPRANAHNVRDWWRRK-EC-HH--HFY-IMN-MMCIVNVFCKCMW-TALFE---YLNPEVY
FSAYH-YDVNWQ-YWHMPMYTCRWM-F-QHFKAAEWQ-CYI-CNQ-T--KDVKYGPRHL-ESDYGQI-C--QNM-A--WE-VT-NICPKYIGWTTQWQLMH-DM-A-DI-CSKMRLFRSGNAMGILFDCNAYESIDKAVFWWGEIFAWVGVPELTFPP-R-DRIRWL-LAWDYQGANPEYV-QYMVMEYI-R-D--YFITTYVWFD-CP-N-PTMQEHDRFALNWL-LGPGMAEMWRQPILGWNKNLNCRYSPHIVQARPYEMYYKNDGIEPLVFNWDRWRIVTI--PYI-----L---------MNKLDM-----CVQ-QN--WAHYNAHTGQGNTKRLGFFSAVEKDSCLCNRYFHFTNMQRQQRPNT-PACYKDLFQVAQI-NCT-QN--DPK-MQQSHARPI-TPCCHGKRRPGLSVVGMCNHYFIPYDHRWDACACRYYPALMSMDNNYCCYCEADHDHQYKH-V-Q----WSSTRPNQAATFHFRGFIYSLIPVLFVNTVNVKAFQVLAEQWEDWRYQIDPFLYKWNKCERHGTSYETELGSTFSPWPSDPETAQVSMKKSADFWSWVWGAWNRMCFEHEQVIAKGSMPWA--P-LKPL-H-RWPPQYY--WCLLRWYKYLNQCTMAMRSCDISYNILMAYNRMHVGREVAMRNKDEH-DLSRLRSHYVD-DKAMYL-IEEKCWHWPMNLYALVLHVAYTPCGKALW-WYASTWNCASNKWQIDAVYRHHQTTGRK-YGYRRPRSF-FMKIQFIGDYSQLFSEGGPWPKAQSTHFTWTDILYLMFLGPMPSKMDEKMMIAWDQ-VGFRWVKGKTFQVRKPPHFDELKRFSDNICCMQGFEPFDPAMCQ-QWHPVFHGSGWKRMVLSMDRGMPSIRTKILACTQKPGQYQRINHPLLIAVGDYTYVLWYTSIWQRSTYVAPKVF''')


# 1.3.3 - Edit Distance
if run(3):
   score = editDistance('PLEASANTLY', 'MEANLY')
   score |> testVs(5)

   l = readlines('dataset_248_3.txt')
   score = editDistance(l[0], l[1])
   score |> testVs(326)


# 1.3.5 - Fitting Alignment Problem
if run(4):
   score, s = fitAlignment('GTAGGCTTAAGGTTA', 'TAGATA')
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''2
TAGGCTTA
TAGA-T-A''')

   l = readlines('dataset_248_5.txt')
   score, s = fitAlignment(l[0], l[1])
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''17
ACCGTATAAGTACC-TAGCC-GT-G-TTAAGCATCTA-TCTGTATC-CGCTTGCTTGATGAATAACCTT-G-TTAGCTAAG-AGGATGAGAGTCTT-GTGGGCTC
ACGGT-TATGCACCCT-GCGAGTTGGTTCCGCAGGTAATCT-TAAAACG---G-TA-ATGGCCA-CCTTAGGTTCGCG--GCAGCAT-ATAGACTTAGCCGGTTC''')


# 1.3.7 - Overlap Alignment Problem
if run(5):
   score, s = overlapAlignment('PAWHEAE', 'HEAGAWGHEE')
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''1
HEAE
HEA-''')

   l = readlines('dataset_248_7.txt')
   score, s = overlapAlignment(l[0], l[1])
   f"{score}\n{s[0]}\n{s[1]}" |> testVs('''17
TACTAGCCTAGT-CTAATCCGTGCCTATT-GCTGCTACTTCCG-TTAGACGGAGTG-CCGCGTCTTCGTGCCGGTC-TAGT-TCTAAGAG-TCCGACGTGTGTTAAGCTGATCAGG-GTTTTCTCCT-GCG-AGGATTTATTGAG-GCACGGGGCTCAGACAATT-ATG-CAAATGCTTAGTCCGT-GTTTAA--TCTGATCGTCAAAGTAGGTGGTT--ATCCGGCAGCTGCGTTGATCC-TCACTCTTA-TCCACACTTGGTTTCCT
TACT-GACTAATTCTGATCCGTCCCTATTTGCTGGG-CTTCCGGTTGGACA-ACTTACCGCGTC--C-TACCGGTGATAGCGT-TAA-AGGTT-GACGCGTGC---GCTGATTAAGAGTAT-C-CCTAGCGCAGCCTT-ATCGCGCGCACGAGGC-CAT-CGATTCATAACAAATGGTTTGTCCATCGCTGAACATCTGATCGTTAA-GCGGGTGCTTGGATC-GGCGGCTGCGTTGA-CCGTTACT-TGCGTCCATACTTG-TT-CCT''')
